name: "CUnit Tests"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository with Submodules
        uses: actions/checkout@v3
        with:
          submodules: true  # This ensures submodules are cloned

      - name: Install CUnit
        run: sudo apt-get install -y libcunit1 libcunit1-doc libcunit1-dev

      - name: Build and Run Tests
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ctest --output-on-failure
